import { Album } from "./album"

export const ALBUMS: Album[] = [
  {
    name: "The Low End Theory",
    artist: "A Tribe Called Quest",
    releaseDate: new Date(1991, 8, 24),
    image: "/the-low-end-theory.jpeg",
    region: "Queens, New York",
    label: "Jive",
    whyItMatters: "A jazz-rap benchmark that made low-end warmth and conversational rhymes feel effortless.",
  },
  {
    name: "Midnight Marauders",
    artist: "A Tribe Called Quest",
    releaseDate: new Date(1993, 10, 9),
    image: "/midnight-marauders.jpeg",
    region: "Queens, New York",
    label: "Jive",
    whyItMatters: "It sharpened Tribe's breezy chemistry into one of hip-hop's most beloved front-to-back listens.",
  },
  {
    name: "Doin' Thangs",
    artist: "Big Bear",
    releaseDate: new Date(1998, 6, 14),
    image: "/doin-thangs.jpeg",
    region: "Baton Rouge, Louisiana",
    label: "Big Bear Entertainment",
    whyItMatters: "A cult Southern rap artifact whose cover became almost as legendary as the record itself.",
  },
  {
    name: "My Turn to Eat",
    artist: "Big Kuntry King",
    releaseDate: new Date(2008, 8, 30),
    image: "/my-turn-to-eat.jpeg",
    region: "Atlanta, Georgia",
    label: "Grand Hustle",
    whyItMatters: "A snapshot of Grand Hustle's post-mixtape expansion and Atlanta's late-2000s dominance.",
  },
  {
    name: "E. 1999 Eternal",
    artist: "Bone Thugs-N-Harmony",
    releaseDate: new Date(1995, 7, 25),
    image: "/e-1999-eternal.jpeg",
    region: "Cleveland, Ohio",
    label: "Ruthless",
    whyItMatters: "It turned rapid melodic flows and mournful harmonies into a massive commercial blueprint.",
  },
  {
    name: "Confessions of Fire",
    artist: "Cam'ron",
    releaseDate: new Date(1998, 7, 21),
    image: "/confessions-of-fire.jpeg",
    region: "Harlem, New York",
    label: "Untertainment / Epic",
    whyItMatters: "Cam's debut catches Harlem flash before the Dipset era fully took shape.",
  },
  {
    name: "Hit Em Where It Hurt",
    artist: "Criminal Elament",
    releaseDate: new Date(1993, 0, 1),
    image: "/hit-em-where-it-hurt.jpeg",
    region: "Houston, Texas",
    label: "Cartel",
    whyItMatters: "A deep-cut Houston release with the kind of regional texture collectors chase.",
  },
  {
    name: "3 Feet High and Rising",
    artist: "De La Soul",
    releaseDate: new Date(1989, 2, 3),
    image: "/3-feet-high-and-rising.png",
    region: "Long Island, New York",
    label: "Tommy Boy",
    whyItMatters: "It blew open hip-hop's imagination with skits, samples, color, and oddball charm.",
  },
  {
    name: "The Dude",
    artist: "Devin",
    releaseDate: new Date(1998, 5, 16),
    image: "/the-dude.jpeg",
    region: "Houston, Texas",
    label: "Rap-A-Lot",
    whyItMatters: "Devin's smoked-out humor and soul made him one of rap's great character writers.",
  },
  {
    name: "The Chronic",
    artist: "Dr. Dre",
    releaseDate: new Date(1992, 11, 15),
    image: "/the-chronic.jpeg",
    region: "Los Angeles, California",
    label: "Death Row / Interscope",
    whyItMatters: "The definitive G-funk statement, reshaping West Coast rap and mainstream production.",
  },
  {
    name: "The Score",
    artist: "The Fugees",
    releaseDate: new Date(1996, 1, 13),
    image: "/the-score.jpeg",
    region: "New Jersey",
    label: "Ruffhouse / Columbia",
    whyItMatters: "A crossover classic that balanced sharp rapping, reggae textures, and huge pop instincts.",
  },
  {
    name: "For the Hell of It",
    artist: "Hell Rell",
    releaseDate: new Date(2007, 8, 25),
    image: "/for-the-hell-of-it.jpeg",
    region: "Bronx, New York",
    label: "Diplomat / Koch",
    whyItMatters: "A rugged Dipset branch release from the crew's mixtape-to-retail afterglow.",
  },
  {
    name: "D.I.R.T. (Da Incredible Rap Team)",
    artist: "Heltah Skeltah",
    releaseDate: new Date(2008, 8, 30),
    image: "/da-incredible-rap-team.jpeg",
    region: "Brooklyn, New York",
    label: "Duck Down",
    whyItMatters: "A late Boot Camp Clik reunion that keeps the duo's grimy chemistry alive.",
  },
  {
    name: "Amerikkka's Most Wanted",
    artist: "Ice Cube",
    releaseDate: new Date(1990, 5, 16),
    image: "/amerikkkas-most-wanted.jpeg",
    region: "Los Angeles, California",
    label: "Priority",
    whyItMatters: "Cube's solo debut fused West Coast fury with Bomb Squad chaos and political bite.",
  },
  {
    name: "Reasonable Doubt",
    artist: "Jay Z",
    releaseDate: new Date(1996, 5, 25),
    image: "/reasonable-doubt.jpeg",
    region: "Brooklyn, New York",
    label: "Roc-A-Fella / Priority",
    whyItMatters: "The mafioso-rap jewel that introduced Jay's cool precision and hustler mythology.",
  },
  {
    name: "The Blueprint",
    artist: "Jay Z",
    releaseDate: new Date(2001, 8, 11),
    image: "/the-blueprint.jpeg",
    region: "Brooklyn, New York",
    label: "Roc-A-Fella / Def Jam",
    whyItMatters: "It reset Jay's sound with soul chops, relaxed authority, and blockbuster confidence.",
  },
  {
    name: "400 Degreez",
    artist: "Juvenile",
    releaseDate: new Date(1998, 11, 3),
    image: "/400-degreez.jpeg",
    region: "New Orleans, Louisiana",
    label: "Cash Money / Universal",
    whyItMatters: "A bounce-powered breakthrough that pushed New Orleans rap into the national spotlight.",
  },
  {
    name: "Justicizms",
    artist: "Kool & Deadly",
    releaseDate: new Date(1987, 0, 1),
    image: "/justicizms.jpeg",
    region: "Los Angeles, California",
    label: "Kru-Cut",
    whyItMatters: "A rare early West Coast curio from the era when regional rap identities were still forming.",
  },
  {
    name: "K9 Posse",
    artist: "K9 Posse",
    releaseDate: new Date(1988, 0, 1),
    image: "/k9-posse.jpeg",
    region: "New York, New York",
    label: "Arista",
    whyItMatters: "An oddball late-80s snapshot where novelty, style, and beatbox-era energy collide.",
  },
  {
    name: "The Wonderful World of Cease A Leo",
    artist: "Lil' Cease",
    releaseDate: new Date(1999, 2, 23),
    image: "/the-wonderful-world-of-cease-a-leo.jpeg",
    region: "Brooklyn, New York",
    label: "Undeas / Atlantic",
    whyItMatters: "A post-Biggie Junior M.A.F.I.A. document full of late-90s Bad Boy shine.",
  },
  {
    name: "The Leprechaun",
    artist: "Lil Flip",
    releaseDate: new Date(2000, 6, 18),
    image: "/the-leprechaun.jpeg",
    region: "Houston, Texas",
    label: "Sucka Free",
    whyItMatters: "The underground Houston breakthrough that set up Flip's freestyle king reputation.",
  },
  {
    name: "Operation: Doomsday",
    artist: "MF Doom",
    releaseDate: new Date(1999, 1, 1),
    image: "/operation-doomsday.jpeg",
    region: "Long Island, New York",
    label: "Fondle 'Em",
    whyItMatters: "The masked rebirth of DOOM, turning grief, cartoons, and dusty loops into mythology.",
  },
  {
    name: "The Infamous",
    artist: "Mobb Deep",
    releaseDate: new Date(1995, 3, 25),
    image: "/the-infamous.jpeg",
    region: "Queens, New York",
    label: "Loud / RCA",
    whyItMatters: "A cold, claustrophobic Queensbridge masterpiece that defined street-rap atmosphere.",
  },
  {
    name: "Ronald Dregan",
    artist: "Mac Dre",
    releaseDate: new Date(2004, 6, 20),
    image: "/ronald-dregan.jpeg",
    region: "Vallejo, California",
    label: "Thizz Entertainment",
    whyItMatters: "A hyphy-era pillar that captures Mac Dre's humor, charisma, and Bay Area bounce.",
  },
  {
    name: "Ghetto D",
    artist: "Master P",
    releaseDate: new Date(1997, 8, 2),
    image: "/ghetto-d.jpeg",
    region: "New Orleans, Louisiana",
    label: "No Limit / Priority",
    whyItMatters: "No Limit's tank at full speed: independent hustle turned into rap empire.",
  },
  {
    name: "Blackstar",
    artist: "Mos Def & Talib Kweli",
    releaseDate: new Date(1998, 8, 29),
    image: "/blackstar.jpeg",
    region: "Brooklyn, New York",
    label: "Rawkus",
    whyItMatters: "A Rawkus-era landmark for thoughtful, nimble Brooklyn lyricism.",
  },
  {
    name: "Illmatic",
    artist: "Nas",
    releaseDate: new Date(1994, 3, 19),
    image: "/illmatic.jpeg",
    region: "Queens, New York",
    label: "Columbia",
    whyItMatters: "A standard-setting debut where every verse feels carved into New York rap history.",
  },
  {
    name: "Stillmatic",
    artist: "Nas",
    releaseDate: new Date(2001, 11, 18),
    image: "/stillmatic.jpeg",
    region: "Queens, New York",
    label: "Ill Will / Columbia",
    whyItMatters: "Nas' comeback statement, restoring his edge during one of rap's great rivalries.",
  },
  {
    name: "Nastradamus",
    artist: "Nas",
    releaseDate: new Date(1999, 10, 23),
    image: "/nastradamus.jpeg",
    region: "Queens, New York",
    label: "Columbia",
    whyItMatters: "A late-90s Nas time capsule from his most commercially pressured stretch.",
  },
  {
    name: "Ready to Die",
    artist: "Notorious B.I.G.",
    releaseDate: new Date(1994, 8, 13),
    image: "/ready-to-die.jpeg",
    region: "Brooklyn, New York",
    label: "Bad Boy / Arista",
    whyItMatters: "Biggie's cinematic debut made Brooklyn menace, humor, and vulnerability feel enormous.",
  },
  {
    name: "Straight Outta Compton",
    artist: "N.W.A.",
    releaseDate: new Date(1988, 7, 8),
    image: "/straight-outta-compton.jpeg",
    region: "Compton, California",
    label: "Ruthless / Priority",
    whyItMatters: "A detonator for gangsta rap and one of hip-hop's most confrontational breakthroughs.",
  },
  {
    name: "Aquemini",
    artist: "Outkast",
    releaseDate: new Date(1998, 8, 29),
    image: "/aquemini.jpeg",
    region: "Atlanta, Georgia",
    label: "LaFace / Arista",
    whyItMatters: "Outkast's cosmic Southern masterpiece proved Atlanta could stretch rap's whole universe.",
  },
  {
    name: "Funky As I Wanna Be",
    artist: "Pooh Man",
    releaseDate: new Date(1992, 0, 1),
    image: "/funky-as-i-wanna-be.jpeg",
    region: "Oakland, California",
    label: "Jive",
    whyItMatters: "A Bay Area street-rap release with the funk-heavy regional flavor of its moment.",
  },
  {
    name: "Fear of a Black Planet",
    artist: "Public Enemy",
    releaseDate: new Date(1990, 3, 10),
    image: "/fear-of-a-black-planet.jpeg",
    region: "Long Island, New York",
    label: "Def Jam / Columbia",
    whyItMatters: "A dense, radical, sample-storm classic that made protest music sound explosive.",
  },
  {
    name: "Only Built 4 Cuban Linx",
    artist: "Raekwon",
    releaseDate: new Date(1995, 7, 1),
    image: "/only-built-4-cuban-linx.jpeg",
    region: "Staten Island, New York",
    label: "Loud / RCA",
    whyItMatters: "The purple-tape crime saga that turned Wu-Tang mythology into cinematic street opera.",
  },
  {
    name: "Liquid Swords",
    artist: "RZA",
    releaseDate: new Date(1995, 11, 7),
    image: "/liquid-swords.jpeg",
    region: "Staten Island, New York",
    label: "Geffen",
    whyItMatters: "A razor-sharp Wu solo classic with icy production and chessboard lyricism.",
  },
  {
    name: "The Diary",
    artist: "Scarface",
    releaseDate: new Date(1994, 9, 18),
    image: "/the-diary.jpeg",
    region: "Houston, Texas",
    label: "Rap-A-Lot",
    whyItMatters: "Scarface's bleakest writing turned paranoia and mortality into Southern rap scripture.",
  },
  {
    name: "Doggystyle",
    artist: "Snoop Dogg",
    releaseDate: new Date(1993, 10, 23),
    image: "/doggystyle.jpeg",
    region: "Long Beach, California",
    label: "Death Row / Interscope",
    whyItMatters: "A relaxed, melodic G-funk blockbuster that made Snoop an instant icon.",
  },
  {
    name: "Give It 2 'Em Raw",
    artist: "Soulja Slim",
    releaseDate: new Date(1998, 4, 19),
    image: "/give-it-2-em-raw.jpeg",
    region: "New Orleans, Louisiana",
    label: "No Limit / Priority",
    whyItMatters: "A raw No Limit street record powered by Slim's urgent, unmistakable voice.",
  },
  {
    name: "Da Baddest Bitch",
    artist: "Trina",
    releaseDate: new Date(2000, 2, 21),
    image: "/da-baddest-bitch.jpeg",
    region: "Miami, Florida",
    label: "Slip-N-Slide / Atlantic",
    whyItMatters: "A bold Miami debut that carved out space for Trina's unapologetic star persona.",
  },
  {
    name: "All Eyez on Me",
    artist: "Tupac",
    releaseDate: new Date(1996, 1, 13),
    image: "/all-eyez-on-me.jpeg",
    region: "Los Angeles, California",
    label: "Death Row / Interscope",
    whyItMatters: "A sprawling double-album event that captured Pac at his most magnetic and combustible.",
  },
  {
    name: "Enter the Wu-Tang (36 Chambers)",
    artist: "Wu-Tang Clan",
    releaseDate: new Date(1993, 10, 9),
    image: "/36-chambers.jpeg",
    region: "Staten Island, New York",
    label: "Loud / RCA",
    whyItMatters: "A raw crew manifesto that changed rap slang, production, business, and mythology.",
  },
]

export const SORT_METHODS = [
  {
    name: "artist_a_to_z",
    method: (a: Album, b: Album) => {
      return a.artist > b.artist ? 1 : -1
    },
  },
  {
    name: "album_a_to_z",
    method: (a: Album, b: Album) => {
      return a.name > b.name ? 1 : -1
    },
  },
  {
    name: "release_old_to_new",
    method: (a: Album, b: Album) => {
      return a.releaseDate > b.releaseDate ? 1 : -1
    },
  },
]
